# Generated by Django 6.1 on 2026-08-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0012_space_publication_status_recurringavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('seeking', "Recherche d'un établissement"), ('matched', 'Projet mis en relation'), ('active', 'Accueil en cours'), ('closed', 'Terminé')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworking_projects', to='spaces.carehome')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
