# Generated by Django 6.1 on 2026-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='space',
            name='location',
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
