# Generated by Django 6.1 on 2026-08-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_space_capacity_remove_space_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='availability',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.TextField(),
        ),
    ]
