# Generated by Django 6.1 on 2026-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_space_availability_alter_space_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the space', null=True, upload_to='spaces/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='space',
            name='image_alt_text',
            field=models.CharField(blank=True, default='', help_text='Alternative text for the image', max_length=500),
        ),
    ]
