# Generated by Django 6.1 on 2026-08-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_space_image_space_image_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='image',
        ),
        migrations.RemoveField(
            model_name='space',
            name='image_alt_text',
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the space', upload_to='spaces/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Alternative text for the image', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.space')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
