# Generated by Django 6.1 on 2026-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_remove_space_image_remove_space_image_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='availability',
            field=models.TextField(default=''),
        ),
    ]
