# Generated by Django 6.1 on 2026-08-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_space_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('city_code', models.CharField(blank=True, default='', max_length=16)),
                ('department_code', models.CharField(blank=True, default='', max_length=8)),
                ('department_name', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ban_id', models.CharField(blank=True, default='', max_length=64)),
                ('ban_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'postal_code', 'label'],
            },
        ),
        migrations.AddField(
            model_name='carehome',
            name='address_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_homes', to='spaces.address'),
        ),
    ]
