# Generated by Django 6.1 on 2026-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_address_carehome_address_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
