# Generated by Django 6.1 on 2026-08-29 12:26

from django.db import migrations, models


def normalize_for_search(value):
    import re
    import unicodedata

    if not value:
        return ""
    normalized = unicodedata.normalize("NFKD", value)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    lowered = ascii_text.lower()
    words_only = re.sub(r"[^a-z0-9]+", " ", lowered)
    return " ".join(words_only.split())


def populate_search_text(apps, schema_editor):
    Address = apps.get_model("spaces", "Address")
    for address in Address.objects.all():
        address.search_text = normalize_for_search(
            " ".join(
                [
                    address.raw_address or "",
                    address.label or "",
                    address.city or "",
                    address.postal_code or "",
                    address.city_code or "",
                    address.department_code or "",
                    address.department_name or "",
                    address.region_name or "",
                ]
            )
        )
        address.save(update_fields=["search_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_address_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='search_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(populate_search_text, migrations.RunPython.noop),
    ]
