# Generated by Django 6.1 on 2026-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_address_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('limited', 'Limited')], default='available', help_text='Availability status of the space', max_length=20),
        ),
    ]
