# Generated by Django 6.1 on 2026-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_space_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carehome',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email address of the contact person', max_length=254),
        ),
        migrations.AddField(
            model_name='carehome',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of the contact person', max_length=200),
        ),
        migrations.AddField(
            model_name='carehome',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='Name of the parent organization or group', max_length=200),
        ),
        migrations.AddField(
            model_name='carehome',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('associatif', 'Associatif'), ('public', 'Public'), ('prive', 'Privé')], default='', help_text='Legal status of the organization', max_length=20),
        ),
    ]
