# Generated by Django 6.1 on 2026-08-30 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EhpadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=200)),
                ('establishment_address', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('participates_in_spaces', models.BooleanField(default=False)),
                ('participates_in_coworking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ehpad_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
